### ISSUE TITLE
Cannot add donation even the name and email is true

### ISSUE THREAD

**Issue by narusaka0701** [TanJeeSchuan/Data-Structure-Assignment#4]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "entity.DonationManagement.addDonation(entity.Donor, entity.CharityCause, double)" because "this.dm" is null

这个是在donation management controller 的

for (int i = 0; i < donorSet.size(); i++) {
            System.out.println(donor);
            if (donorSet.getValue(i).equals(donor)) {
                System.out.println(456);
                isExist = true;
            }
        }
        if (!isExist) {
            System.out.println(789);
            DB.getInstance().donorDAO.addDonor(donor);
        }

        dm.addDonation(donor, cause, amount);

        donationManagementUI.promptSuccessMessage("added");
        
        我print 了在if selection,他就是没有run 到 if (donorSet.getValue(i).equals(donor)) 
        但我print donorSet.getValue 和 donor都有一样的名字
        
        然后我check了，donorSet.getValue(i) 的john smith 的id = 2, 但是donor的john smith 的 id = 12,难道是这个

**Comment by narusaka0701** [comment]
private void displayAllDonees() {
        LinkedSet<Donee> doneeSet = db.doneeDAO.getDonees();
        ArrayList<CharityCause> causes = db.charityCauseDAO.getCharityCauses();
        String causeName = null;
        ArrayList<String> doneesInfo = new ArrayList<>();
        doneesInfo.add("%-3s | %-20s | %-30s% | %-11s | %-50s".formatted("No.", "Donee Name", "Cause", "Contact Number", "Address"));
        System.out.println(123);
        for (int i = 0; i < doneeSet.size(); i++) {
            causeName = null;
            for (int j = 0; j < causes.size() && causeName == null; j++) {
                CharityCause cause = (CharityCause) causes.get(j);
                
                System.out.println(cause.donees);
                if (cause.donees.contains(doneeSet.getValue(i))) {
                    causeName = cause.getCauseName();
                }
            }
            doneesInfo.add("%-3d | %-20s | %-30s% | %-11s | %-50s".formatted(i + 1, doneeSet.getValue(i).getName(), causeName, doneeSet.getValue(i).getContactNumber(), doneeSet.getValue(i).getAddress()));

        }

        doneeSystemUI.showDonees(doneesInfo);
    }
this function got problem as this function cannot display and list out the donee information

**Comment by TanJeeSchuan** [comment]
Fixed
